networks:
  dev:

services:

  ui-template-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.dev
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      UI_SERVICE_URL: ${UI_SERVICE_URL}
    ports:
      - "${UI_SERVICE_PORT}:${UI_SERVICE_PORT}"
    command: ["java", "-jar", "ui-template-service.jar", "--spring.profiles.active=${SPRING_PROFILES_ACTIVE}"]
    networks:
      - dev
