server:
    port: 8080

my-service:
    url: http://81.94.158.164:8080

thymeleaf:
    cache: true

spring:
    devtools:
        restart:
            enabled: false # отключаем devtools в проде, чтобы не перезагружать лишний раз
