spring:
    application:
        name: ui-service
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
    profiles:
        active: dev

logging:
    level:
        root: INFO # уровень логирования по умолчанию
        org.springframework.web: DEBUG # логирование для spring web
        itmo.denilll: DEBUG # логирование для пакета

# Общие настройки безопасности (если используется Spring Security)
#spring:
#    security:
#        user:
#            name: admin  # Логин по умолчанию
#            password: secret  # Пароль по умолчанию
