server:
    port: 8080

my-service:
    url: http://localhost:8080

thymeleaf:
    cache: false # отключаем чтобы изменения в шаблонах применялись без перезапуска приложения

spring:
    devtools:
        restart:
            enabled: true
